spring.application.name=Bazzar

#Conexion de BD
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Xbox.360*

#hubernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=bazaar-2026-clave-secreta-para-desarrollo-local-prueba-uno
jwt.expiracion=86400000